### ISSUE TITLE
Refactor PigResource.java

### ISSUE THREAD

**Issue by amihaiemil** [eBay/oink#3]
[This](https://github.com/eBay/oink/blob/master/service/src/main/java/org/pig/oink/rest/PigResource.java) class could be refactored in a number of ways, including: 

1) use constants from ``java.net.HttpURLConnection`` to remove magic numbers from Responses; also methods like ``Response.serverError()`` can get rid of ``500``

2) As explained [here](https://jersey.java.net/documentation/latest/representations.html#d0e6754), exception handling can be done more elegantly. I would declare some exception handlers and get rid of all the try catches, or at least most of them. 

Also, I wouldn't throw HTTP 409 since it's a more complicated scenario for it (see [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)); I would throw 500 server error or throw HTTP 412 (precondition failed; usually as a result of validation failures) 

3) There seems to be duplicated code for ``try { ... } catch (IOException)`` (2 nested catch for the same exception) inside ``public Response registerScript(...)``

If agreed upon these changes, I could make a PR as soon as I have a little time.

**Comment by rucshah** [comment]
Please go ahead and submit PR.

**Comment by amihaiemil** [comment]
@rucshah PR #4 is for this. The changes are structured in 3 commits.

I wrote a detailed description of the PR and also left some line comments. I hope everything makes sense. If not, don't hesitate to ask, I'll answer as soon as possible
